### PR TITLE
Image Optimization, CSS & JS Minification

### PR DESCRIPTION
**Pull request by bhubbard**
- Optimized Images (Used codekit)
- Setup Sass files, and minimized CSS for performance (Used codekit)
- Minimized JS for performance (Used codekit)
- The biggest item needing a look over are the php notices I fixed in "includes/srp-profile.php". I tested after the update, didn't see any issues with the fix, but I don't know the complete in/outs of this plugin yet.

### CODE REVIEW

**Comment by maxchirkov** [comment]
Just a heads up: I did merge your changes into my development branch, but there is more work needs to be done before I can release an update. I checked all main widgets, while most of them work, I see that map and neighborhoods don't work correctly any longer, so I need to fix those before releasing an update.

**Comment by bhubbard** [comment]
@maxchirkov I just pushed up a fix for the map and neighborhood shortcode, although with debug on I notice I get lots of Strict Standards errors:

Strict Standards: Accessing static property srpWidgets::$widgets as non static in /wp-content/plugins/simple-real-estate-pack/includes/Class_srpWidgets.php on line 28

Strict Standards: Accessing static property srpWidgets::$widgets as non static in /wp-content/plugins/simple-real-estate-pack/includes/Class_srpWidgets.php on line 30

Strict Standards: Accessing static property srpWidgets::$widgets as non static in /wp-content/plugins/simple-real-estate-pack/includes/Class_srpWidgets.php on line 176

Strict Standards: Accessing static property srpWidgets::$widgets as non static in /wp-content/plugins/simple-real-estate-pack/includes/Class_srpWidgets.php on line 180

Strict Standards: Accessing static property srpWidgets::$widgets as non static in /wp-content/plugins/simple-real-estate-pack/includes/srp-profile.php on line 194

Strict Standards: Accessing static property srpWidgets::$widgets as non static in /wp-content/plugins/simple-real-estate-pack/includes/Class_srpWidgets.php on line 92

Strict Standards: Accessing static property srpWidgets::$widgets as non static in /wp-content/plugins/simple-real-estate-pack/includes/Class_srpWidgets.php on line 94

**Comment by bhubbard** [comment]
@maxchirkov - Was wonder if you got to test again. I believe the changes should be good enough for an update as those Strict Standards issues were there before the changes I made.

**Comment by maxchirkov** [comment]
Hi Brandon, sorry for the delay. I saw you push request, but I just can't
find a minute of time to get this tested. I'm hoping to get this looked
over in the next few days.

Max Chirkov

**Comment by maxchirkov** [comment]
Hi Brandon, I noticed a new file that I don't recognize: js/jsmin.js - what is it?

**Comment by maxchirkov** [comment]
Just FYI - I added Gulp to compile sass and minify css.

**Comment by bhubbard** [comment]
@maxchirkov 

Yeah you can go ahead and delete that file. I had used [CodeKit](https://incident57.com/codekit/) to optimize all the images and minify the css and js. That file got created off the default settings, I just forgot to delete it. I will use Gulp going forward, now that you have added it.

**Pull request merged**
